//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CafeCMU.Module.BusinessObjects.CafeCMU
{

    [DefaultProperty("TenSP")]
    public partial class Sanpham : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fTenSP;
        [Size(30)]
        [DevExpress.Xpo.DisplayName(@"Tên sản phẩm")]
        public string TenSP
        {
            get { return fTenSP; }
            set { SetPropertyValue<string>(nameof(TenSP), ref fTenSP, value); }
        }
        string fDvt;
        [Size(10)]
        public string Dvt
        {
            get { return fDvt; }
            set { SetPropertyValue<string>(nameof(Dvt), ref fDvt, value); }
        }
        decimal fGiaban;
        [DevExpress.Xpo.DisplayName(@"Giá bán")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal Giaban
        {
            get { return fGiaban; }
            set { SetPropertyValue<decimal>(nameof(Giaban), ref fGiaban, value); }
        }
        [Association(@"HoadonCTReferencesSanpham"), Aggregated]
        public XPCollection<HoadonCT> HoadonCTs { get { return GetCollection<HoadonCT>(nameof(HoadonCTs)); } }
    }

}
